CLIP_PLAY_TIME: 10
CLIP_START_INTERVAL:
- 15
- 75
CUSTOMER_PO_TOKEN:
  po_token: ''
  visitor_data: ''
DEFAULT_COMMENT_PLACEHOLDERS: false
DOWNLOADER: bilibili
DOWNLOAD_HIGH_RES: false
FULL_LAST_CLIP: false
HTTP_PROXY: 127.0.0.1:7890
NO_BILIBILI_CREDENTIAL: false
ONLY_GENERATE_CLIPS: false
PROXY_ADDRESS: 192.168.1.2:7788
SEARCH_MAX_RESULTS: 4
SEARCH_WAIT_TIME: !!python/tuple
- 1
- 11
USER_ID: Sian
USER_ID_RAW: Sian
USE_ALL_CACHE: false
USE_AUTO_PO_TOKEN: true
USE_CUSTOM_PO_TOKEN: false
USE_OAUTH: true
USE_PROXY: false
VIDEO_BITRATE: 5000
VIDEO_RES: !!python/tuple
- 1920
- 1080
VIDEO_TRANS_ENABLE: true
VIDEO_TRANS_TIME: 0.6
